/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LayoutContent: typeof import('./../src/components/LayoutContent.vue')['default']
    LayoutFooter: typeof import('./../src/components/LayoutFooter.vue')['default']
    LayoutHeader: typeof import('./../src/components/LayoutHeader.vue')['default']
    LayoutSider: typeof import('./../src/components/LayoutSider.vue')['default']
    LayoutTab: typeof import('./../src/components/LayoutTab.vue')['default']
  }
}
